var JS = require("jstest")
require("./buzzer_spec")
require("./mock_spec")
require("./announcer_spec")
require("./counter_spec")
require("./accumulator_spec")
require("./counting_spec")
require("./person_spec")
JS.Test.autorun()

